[2020-06-01 14:47:03,643] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: bq_data_v1.bq_write_to_test 2020-05-31T09:00:00+00:00 [queued]>
[2020-06-01 14:47:03,647] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: bq_data_v1.bq_write_to_test 2020-05-31T09:00:00+00:00 [queued]>
[2020-06-01 14:47:03,647] {__init__.py:1353} INFO - 
--------------------------------------------------------------------------------
[2020-06-01 14:47:03,647] {__init__.py:1354} INFO - Starting attempt 3 of 4
[2020-06-01 14:47:03,647] {__init__.py:1355} INFO - 
--------------------------------------------------------------------------------
[2020-06-01 14:47:03,654] {__init__.py:1374} INFO - Executing <Task(BigQueryOperator): bq_write_to_test> on 2020-05-31T09:00:00+00:00
[2020-06-01 14:47:03,654] {base_task_runner.py:119} INFO - Running: ['airflow', 'run', 'bq_data_v1', 'bq_write_to_test', '2020-05-31T09:00:00+00:00', '--job_id', '31', '--raw', '-sd', 'DAGS_FOLDER/bq_data_v1.py', '--cfg_path', '/var/folders/y6/nhshp1rd3kj1kwtclmvq1nfsrtp362/T/tmpzr6lecc4']
[2020-06-01 14:47:04,412] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test [2020-06-01 14:47:04,411] {__init__.py:51} INFO - Using executor SequentialExecutor
[2020-06-01 14:47:04,632] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test [2020-06-01 14:47:04,631] {__init__.py:305} INFO - Filling up the DagBag from /Users/rebecca.vickery/Documents/Github/airflow_sandbox/airflow/dags/bq_data_v1.py
[2020-06-01 14:47:04,985] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test [2020-06-01 14:47:04,985] {cli.py:517} INFO - Running <TaskInstance: bq_data_v1.bq_write_to_test 2020-05-31T09:00:00+00:00 [running]> on host HX3286T2.local
[2020-06-01 14:47:05,005] {bigquery_operator.py:184} INFO - Executing: 
    #standardSQL
            select date, 
    sum(total_confirmed_cases) as total_confirmed_cases
    from bigquery-public-data:covid19_italy.data_by_region
    where DATE(date) = '2020-05-31'
    group by date
    
[2020-06-01 14:47:08,429] {__init__.py:1580} ERROR - BigQuery job failed. Final error was: {'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ":" at [5:30]'}. The job was: {'kind': 'bigquery#job', 'etag': '+Gf7Btvb2zGCkbKgLnMczQ==', 'id': 'sandbox-278915:US.job_ssikIRhh0LtXSYwL-WAKHMA5fO0c', 'selfLink': 'https://bigquery.googleapis.com/bigquery/v2/projects/sandbox-278915/jobs/job_ssikIRhh0LtXSYwL-WAKHMA5fO0c?location=US', 'user_email': 'airflow-sandbox@sandbox-278915.iam.gserviceaccount.com', 'configuration': {'query': {'query': "\n    #standardSQL\n            select date, \n    sum(total_confirmed_cases) as total_confirmed_cases\n    from bigquery-public-data:covid19_italy.data_by_region\n    where DATE(date) = '2020-05-31'\n    group by date\n    ", 'destinationTable': {'projectId': 'sandbox-278915', 'datasetId': 'test', 'tableId': 'covid_test'}, 'createDisposition': 'CREATE_IF_NEEDED', 'writeDisposition': 'WRITE_TRUNCATE', 'priority': 'INTERACTIVE', 'allowLargeResults': True, 'useLegacySql': False, 'timePartitioning': {'type': 'DAY'}}, 'jobType': 'QUERY'}, 'jobReference': {'projectId': 'sandbox-278915', 'jobId': 'job_ssikIRhh0LtXSYwL-WAKHMA5fO0c', 'location': 'US'}, 'statistics': {'creationTime': '1591019227939', 'startTime': '1591019227946', 'endTime': '1591019227946'}, 'status': {'errorResult': {'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ":" at [5:30]'}, 'errors': [{'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ":" at [5:30]'}], 'state': 'DONE'}}
Traceback (most recent call last):
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/contrib/operators/bigquery_operator.py", line 209, in execute
    cluster_fields=self.cluster_fields,
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 849, in run_query
    return self.run_with_configuration(configuration)
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 1248, in run_with_configuration
    format(job['status']['errorResult'], job))
Exception: BigQuery job failed. Final error was: {'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ":" at [5:30]'}. The job was: {'kind': 'bigquery#job', 'etag': '+Gf7Btvb2zGCkbKgLnMczQ==', 'id': 'sandbox-278915:US.job_ssikIRhh0LtXSYwL-WAKHMA5fO0c', 'selfLink': 'https://bigquery.googleapis.com/bigquery/v2/projects/sandbox-278915/jobs/job_ssikIRhh0LtXSYwL-WAKHMA5fO0c?location=US', 'user_email': 'airflow-sandbox@sandbox-278915.iam.gserviceaccount.com', 'configuration': {'query': {'query': "\n    #standardSQL\n            select date, \n    sum(total_confirmed_cases) as total_confirmed_cases\n    from bigquery-public-data:covid19_italy.data_by_region\n    where DATE(date) = '2020-05-31'\n    group by date\n    ", 'destinationTable': {'projectId': 'sandbox-278915', 'datasetId': 'test', 'tableId': 'covid_test'}, 'createDisposition': 'CREATE_IF_NEEDED', 'writeDisposition': 'WRITE_TRUNCATE', 'priority': 'INTERACTIVE', 'allowLargeResults': True, 'useLegacySql': False, 'timePartitioning': {'type': 'DAY'}}, 'jobType': 'QUERY'}, 'jobReference': {'projectId': 'sandbox-278915', 'jobId': 'job_ssikIRhh0LtXSYwL-WAKHMA5fO0c', 'location': 'US'}, 'statistics': {'creationTime': '1591019227939', 'startTime': '1591019227946', 'endTime': '1591019227946'}, 'status': {'errorResult': {'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ":" at [5:30]'}, 'errors': [{'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ":" at [5:30]'}], 'state': 'DONE'}}
[2020-06-01 14:47:08,437] {__init__.py:1603} INFO - Marking task as UP_FOR_RETRY
[2020-06-01 14:47:08,446] {logging_mixin.py:95} INFO - [2020-06-01 14:47:08,446] {configuration.py:287} WARNING - section/key [smtp/smtp_user] not found in config
[2020-06-01 14:47:08,447] {__init__.py:1615} ERROR - Failed to send email to: ['rebeccavickeryds@gmail.com']
[2020-06-01 14:47:08,448] {__init__.py:1616} ERROR - [Errno 61] Connection refused
Traceback (most recent call last):
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/contrib/operators/bigquery_operator.py", line 209, in execute
    cluster_fields=self.cluster_fields,
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 849, in run_query
    return self.run_with_configuration(configuration)
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 1248, in run_with_configuration
    format(job['status']['errorResult'], job))
Exception: BigQuery job failed. Final error was: {'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ":" at [5:30]'}. The job was: {'kind': 'bigquery#job', 'etag': '+Gf7Btvb2zGCkbKgLnMczQ==', 'id': 'sandbox-278915:US.job_ssikIRhh0LtXSYwL-WAKHMA5fO0c', 'selfLink': 'https://bigquery.googleapis.com/bigquery/v2/projects/sandbox-278915/jobs/job_ssikIRhh0LtXSYwL-WAKHMA5fO0c?location=US', 'user_email': 'airflow-sandbox@sandbox-278915.iam.gserviceaccount.com', 'configuration': {'query': {'query': "\n    #standardSQL\n            select date, \n    sum(total_confirmed_cases) as total_confirmed_cases\n    from bigquery-public-data:covid19_italy.data_by_region\n    where DATE(date) = '2020-05-31'\n    group by date\n    ", 'destinationTable': {'projectId': 'sandbox-278915', 'datasetId': 'test', 'tableId': 'covid_test'}, 'createDisposition': 'CREATE_IF_NEEDED', 'writeDisposition': 'WRITE_TRUNCATE', 'priority': 'INTERACTIVE', 'allowLargeResults': True, 'useLegacySql': False, 'timePartitioning': {'type': 'DAY'}}, 'jobType': 'QUERY'}, 'jobReference': {'projectId': 'sandbox-278915', 'jobId': 'job_ssikIRhh0LtXSYwL-WAKHMA5fO0c', 'location': 'US'}, 'statistics': {'creationTime': '1591019227939', 'startTime': '1591019227946', 'endTime': '1591019227946'}, 'status': {'errorResult': {'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ":" at [5:30]'}, 'errors': [{'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ":" at [5:30]'}], 'state': 'DONE'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/models/__init__.py", line 1605, in handle_failure
    self.email_alert(error)
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/models/__init__.py", line 1829, in email_alert
    send_email(self.task.email, subject, html_content)
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/utils/email.py", line 55, in send_email
    mime_subtype=mime_subtype, mime_charset=mime_charset, **kwargs)
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/utils/email.py", line 101, in send_email_smtp
    send_MIME_email(smtp_mail_from, recipients, msg, dryrun)
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/utils/email.py", line 121, in send_MIME_email
    s = smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT) if SMTP_SSL else smtplib.SMTP(SMTP_HOST, SMTP_PORT)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
[2020-06-01 14:47:08,458] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test /Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/contrib/operators/bigquery_operator.py:176: DeprecationWarning: Deprecated parameter `bql` used in Task id: bq_write_to_test. Use `sql` parameter instead to pass the sql to be executed. `bql` parameter is deprecated and will be removed in a future version of Airflow.
[2020-06-01 14:47:08,458] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test   category=DeprecationWarning)
[2020-06-01 14:47:08,462] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test Traceback (most recent call last):
[2020-06-01 14:47:08,463] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/bin/airflow", line 32, in <module>
[2020-06-01 14:47:08,463] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test     args.func(args)
[2020-06-01 14:47:08,463] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2020-06-01 14:47:08,463] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test     return f(*args, **kwargs)
[2020-06-01 14:47:08,463] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/bin/cli.py", line 523, in run
[2020-06-01 14:47:08,463] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test     _run(args, dag, ti)
[2020-06-01 14:47:08,463] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/bin/cli.py", line 442, in _run
[2020-06-01 14:47:08,463] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test     pool=args.pool,
[2020-06-01 14:47:08,463] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/utils/db.py", line 73, in wrapper
[2020-06-01 14:47:08,463] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test     return func(*args, **kwargs)
[2020-06-01 14:47:08,463] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
[2020-06-01 14:47:08,463] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test     result = task_copy.execute(context=context)
[2020-06-01 14:47:08,463] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/contrib/operators/bigquery_operator.py", line 209, in execute
[2020-06-01 14:47:08,463] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test     cluster_fields=self.cluster_fields,
[2020-06-01 14:47:08,463] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 849, in run_query
[2020-06-01 14:47:08,463] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test     return self.run_with_configuration(configuration)
[2020-06-01 14:47:08,463] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 1248, in run_with_configuration
[2020-06-01 14:47:08,463] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test     format(job['status']['errorResult'], job))
[2020-06-01 14:47:08,463] {base_task_runner.py:101} INFO - Job 31: Subtask bq_write_to_test Exception: BigQuery job failed. Final error was: {'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ":" at [5:30]'}. The job was: {'kind': 'bigquery#job', 'etag': '+Gf7Btvb2zGCkbKgLnMczQ==', 'id': 'sandbox-278915:US.job_ssikIRhh0LtXSYwL-WAKHMA5fO0c', 'selfLink': 'https://bigquery.googleapis.com/bigquery/v2/projects/sandbox-278915/jobs/job_ssikIRhh0LtXSYwL-WAKHMA5fO0c?location=US', 'user_email': 'airflow-sandbox@sandbox-278915.iam.gserviceaccount.com', 'configuration': {'query': {'query': "\n    #standardSQL\n            select date, \n    sum(total_confirmed_cases) as total_confirmed_cases\n    from bigquery-public-data:covid19_italy.data_by_region\n    where DATE(date) = '2020-05-31'\n    group by date\n    ", 'destinationTable': {'projectId': 'sandbox-278915', 'datasetId': 'test', 'tableId': 'covid_test'}, 'createDisposition': 'CREATE_IF_NEEDED', 'writeDisposition': 'WRITE_TRUNCATE', 'priority': 'INTERACTIVE', 'allowLargeResults': True, 'useLegacySql': False, 'timePartitioning': {'type': 'DAY'}}, 'jobType': 'QUERY'}, 'jobReference': {'projectId': 'sandbox-278915', 'jobId': 'job_ssikIRhh0LtXSYwL-WAKHMA5fO0c', 'location': 'US'}, 'statistics': {'creationTime': '1591019227939', 'startTime': '1591019227946', 'endTime': '1591019227946'}, 'status': {'errorResult': {'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ":" at [5:30]'}, 'errors': [{'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ":" at [5:30]'}], 'state': 'DONE'}}
[2020-06-01 14:47:08,641] {logging_mixin.py:95} INFO - [2020-06-01 14:47:08,641] {jobs.py:2562} INFO - Task exited with return code 1
