[2020-06-01 15:10:19,140] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: covid_italy_daily.check_public_data_exists 2020-05-31T09:00:00+00:00 [queued]>
[2020-06-01 15:10:19,144] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: covid_italy_daily.check_public_data_exists 2020-05-31T09:00:00+00:00 [queued]>
[2020-06-01 15:10:19,144] {__init__.py:1353} INFO - 
--------------------------------------------------------------------------------
[2020-06-01 15:10:19,144] {__init__.py:1354} INFO - Starting attempt 1 of 1
[2020-06-01 15:10:19,144] {__init__.py:1355} INFO - 
--------------------------------------------------------------------------------
[2020-06-01 15:10:19,150] {__init__.py:1374} INFO - Executing <Task(BigQueryCheckOperator): check_public_data_exists> on 2020-05-31T09:00:00+00:00
[2020-06-01 15:10:19,150] {base_task_runner.py:119} INFO - Running: ['airflow', 'run', 'covid_italy_daily', 'check_public_data_exists', '2020-05-31T09:00:00+00:00', '--job_id', '35', '--raw', '-sd', 'DAGS_FOLDER/covid_italy_daily.py', '--cfg_path', '/var/folders/y6/nhshp1rd3kj1kwtclmvq1nfsrtp362/T/tmp7yf0qhx5']
[2020-06-01 15:10:19,917] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists [2020-06-01 15:10:19,917] {__init__.py:51} INFO - Using executor SequentialExecutor
[2020-06-01 15:10:20,137] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists [2020-06-01 15:10:20,137] {__init__.py:305} INFO - Filling up the DagBag from /Users/rebecca.vickery/Documents/Github/airflow_sandbox/airflow/dags/covid_italy_daily.py
[2020-06-01 15:10:20,513] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists [2020-06-01 15:10:20,513] {cli.py:517} INFO - Running <TaskInstance: covid_italy_daily.check_public_data_exists 2020-05-31T09:00:00+00:00 [running]> on host HX3286T2.local
[2020-06-01 15:10:20,532] {check_operator.py:80} INFO - Executing SQL check: 
                            select count(*) > 0
                            from bigquery-public-data.covid19_italy.data_by_region
                            where DATE(_PARTITIONTIME) = DATE_SUB('2020-05-31', INTERVAL 1 DAY))
                        
[2020-06-01 15:10:20,907] {logging_mixin.py:95} WARNING - /Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py:739: DeprecationWarning: Deprecated parameter `bql` used in `BigQueryBaseCursor.run_query` Use `sql` parameter instead to pass the sql to be executed. `bql` parameter is deprecated and will be removed in a future version of Airflow.
  category=DeprecationWarning)
[2020-06-01 15:10:21,764] {__init__.py:1580} ERROR - BigQuery job failed. Final error was: {'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ")" at [4:96]'}. The job was: {'kind': 'bigquery#job', 'etag': 'DHEmR+Kb9pPoC8Hx6OrqWg==', 'id': 'sandbox-278915:US.job_R8ccm0Kd5BfO0AE7vbCyfjaYyUam', 'selfLink': 'https://bigquery.googleapis.com/bigquery/v2/projects/sandbox-278915/jobs/job_R8ccm0Kd5BfO0AE7vbCyfjaYyUam?location=US', 'user_email': 'airflow-sandbox@sandbox-278915.iam.gserviceaccount.com', 'configuration': {'query': {'query': "\n                            select count(*) > 0\n                            from bigquery-public-data.covid19_italy.data_by_region\n                            where DATE(_PARTITIONTIME) = DATE_SUB('2020-05-31', INTERVAL 1 DAY))\n                        ", 'priority': 'INTERACTIVE', 'useLegacySql': False}, 'jobType': 'QUERY'}, 'jobReference': {'projectId': 'sandbox-278915', 'jobId': 'job_R8ccm0Kd5BfO0AE7vbCyfjaYyUam', 'location': 'US'}, 'statistics': {'creationTime': '1591020621192', 'startTime': '1591020621204', 'endTime': '1591020621204'}, 'status': {'errorResult': {'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ")" at [4:96]'}, 'errors': [{'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ")" at [4:96]'}], 'state': 'DONE'}}
Traceback (most recent call last):
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/operators/check_operator.py", line 81, in execute
    records = self.get_db_hook().get_first(self.sql)
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 138, in get_first
    cur.execute(sql)
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 1821, in execute
    self.job_id = self.run_query(sql)
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 849, in run_query
    return self.run_with_configuration(configuration)
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 1248, in run_with_configuration
    format(job['status']['errorResult'], job))
Exception: BigQuery job failed. Final error was: {'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ")" at [4:96]'}. The job was: {'kind': 'bigquery#job', 'etag': 'DHEmR+Kb9pPoC8Hx6OrqWg==', 'id': 'sandbox-278915:US.job_R8ccm0Kd5BfO0AE7vbCyfjaYyUam', 'selfLink': 'https://bigquery.googleapis.com/bigquery/v2/projects/sandbox-278915/jobs/job_R8ccm0Kd5BfO0AE7vbCyfjaYyUam?location=US', 'user_email': 'airflow-sandbox@sandbox-278915.iam.gserviceaccount.com', 'configuration': {'query': {'query': "\n                            select count(*) > 0\n                            from bigquery-public-data.covid19_italy.data_by_region\n                            where DATE(_PARTITIONTIME) = DATE_SUB('2020-05-31', INTERVAL 1 DAY))\n                        ", 'priority': 'INTERACTIVE', 'useLegacySql': False}, 'jobType': 'QUERY'}, 'jobReference': {'projectId': 'sandbox-278915', 'jobId': 'job_R8ccm0Kd5BfO0AE7vbCyfjaYyUam', 'location': 'US'}, 'statistics': {'creationTime': '1591020621192', 'startTime': '1591020621204', 'endTime': '1591020621204'}, 'status': {'errorResult': {'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ")" at [4:96]'}, 'errors': [{'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ")" at [4:96]'}], 'state': 'DONE'}}
[2020-06-01 15:10:21,790] {__init__.py:1611} INFO - Marking task as FAILED.
[2020-06-01 15:10:21,804] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists Traceback (most recent call last):
[2020-06-01 15:10:21,804] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/bin/airflow", line 32, in <module>
[2020-06-01 15:10:21,804] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists     args.func(args)
[2020-06-01 15:10:21,804] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2020-06-01 15:10:21,804] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists     return f(*args, **kwargs)
[2020-06-01 15:10:21,804] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/bin/cli.py", line 523, in run
[2020-06-01 15:10:21,804] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists     _run(args, dag, ti)
[2020-06-01 15:10:21,804] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/bin/cli.py", line 442, in _run
[2020-06-01 15:10:21,804] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists     pool=args.pool,
[2020-06-01 15:10:21,804] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/utils/db.py", line 73, in wrapper
[2020-06-01 15:10:21,804] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists     return func(*args, **kwargs)
[2020-06-01 15:10:21,804] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
[2020-06-01 15:10:21,804] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists     result = task_copy.execute(context=context)
[2020-06-01 15:10:21,805] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/operators/check_operator.py", line 81, in execute
[2020-06-01 15:10:21,805] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists     records = self.get_db_hook().get_first(self.sql)
[2020-06-01 15:10:21,805] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 138, in get_first
[2020-06-01 15:10:21,805] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists     cur.execute(sql)
[2020-06-01 15:10:21,805] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 1821, in execute
[2020-06-01 15:10:21,805] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists     self.job_id = self.run_query(sql)
[2020-06-01 15:10:21,805] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 849, in run_query
[2020-06-01 15:10:21,805] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists     return self.run_with_configuration(configuration)
[2020-06-01 15:10:21,805] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 1248, in run_with_configuration
[2020-06-01 15:10:21,805] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists     format(job['status']['errorResult'], job))
[2020-06-01 15:10:21,805] {base_task_runner.py:101} INFO - Job 35: Subtask check_public_data_exists Exception: BigQuery job failed. Final error was: {'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ")" at [4:96]'}. The job was: {'kind': 'bigquery#job', 'etag': 'DHEmR+Kb9pPoC8Hx6OrqWg==', 'id': 'sandbox-278915:US.job_R8ccm0Kd5BfO0AE7vbCyfjaYyUam', 'selfLink': 'https://bigquery.googleapis.com/bigquery/v2/projects/sandbox-278915/jobs/job_R8ccm0Kd5BfO0AE7vbCyfjaYyUam?location=US', 'user_email': 'airflow-sandbox@sandbox-278915.iam.gserviceaccount.com', 'configuration': {'query': {'query': "\n                            select count(*) > 0\n                            from bigquery-public-data.covid19_italy.data_by_region\n                            where DATE(_PARTITIONTIME) = DATE_SUB('2020-05-31', INTERVAL 1 DAY))\n                        ", 'priority': 'INTERACTIVE', 'useLegacySql': False}, 'jobType': 'QUERY'}, 'jobReference': {'projectId': 'sandbox-278915', 'jobId': 'job_R8ccm0Kd5BfO0AE7vbCyfjaYyUam', 'location': 'US'}, 'statistics': {'creationTime': '1591020621192', 'startTime': '1591020621204', 'endTime': '1591020621204'}, 'status': {'errorResult': {'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ")" at [4:96]'}, 'errors': [{'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Unexpected ")" at [4:96]'}], 'state': 'DONE'}}
[2020-06-01 15:10:24,141] {logging_mixin.py:95} INFO - [2020-06-01 15:10:24,141] {jobs.py:2562} INFO - Task exited with return code 1
